-- ============================================================
-- EarlyWatch — MySQL schema + seed
-- Import via phpMyAdmin → Import → choose this file → Go
-- Safe to re-run: drops existing tables, recreates, reseeds users.
-- No student data — add students via the API or phpMyAdmin.
-- ============================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE DATABASE IF NOT EXISTS earlywatch
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE earlywatch;

-- ============================================================
-- Drop in reverse dependency order
-- ============================================================
DROP TABLE IF EXISTS interventions;
DROP TABLE IF EXISTS alerts;
DROP TABLE IF EXISTS notes;
DROP TABLE IF EXISTS risk_history;
DROP TABLE IF EXISTS subjects;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS users;

-- ============================================================
-- USERS — auth accounts
-- ============================================================
CREATE TABLE users (
  id           INT AUTO_INCREMENT PRIMARY KEY,
  role         ENUM('adviser','instructor','student') NOT NULL,
  title        VARCHAR(40)  NOT NULL,
  name         VARCHAR(120) NOT NULL,
  initials     VARCHAR(4)   NOT NULL,
  email        VARCHAR(160) NOT NULL UNIQUE,
  password     VARCHAR(255) NOT NULL,          -- plain text for demo; hash in prod
  student_id   VARCHAR(30)  DEFAULT NULL,
  created_at   DATETIME     DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_users_role (role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================
-- STUDENTS
-- ============================================================
CREATE TABLE students (
  id               VARCHAR(30)  PRIMARY KEY,
  name             VARCHAR(120) NOT NULL,
  initials         VARCHAR(4)   NOT NULL,
  course           VARCHAR(120) DEFAULT NULL,
  section          VARCHAR(30)  DEFAULT NULL,
  adviser          VARCHAR(80)  DEFAULT NULL,
  gpa              DECIMAL(3,2) NOT NULL DEFAULT 0,
  attendance       INT          NOT NULL DEFAULT 0,
  missed           INT          NOT NULL DEFAULT 0,
  failed_subjects  INT          NOT NULL DEFAULT 0,
  case_status      ENUM('Open','In-Progress','Monitoring','Resolved')
                                NOT NULL DEFAULT 'Monitoring',
  created_at       DATETIME     DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_students_name     (name),
  INDEX idx_students_section  (section),
  INDEX idx_students_status   (case_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================
-- SUBJECTS — one row per student per subject
-- ============================================================
CREATE TABLE subjects (
  id           INT AUTO_INCREMENT PRIMARY KEY,
  student_id   VARCHAR(30)  NOT NULL,
  code         VARCHAR(20)  NOT NULL,
  name         VARCHAR(160) NOT NULL,
  instructor   VARCHAR(120) DEFAULT NULL,
  grade        INT          DEFAULT NULL,
  prelim       INT          DEFAULT NULL,
  midterm      INT          DEFAULT NULL,
  attendance   INT          DEFAULT 0,
  UNIQUE KEY uq_subject_per_student (student_id, code),
  CONSTRAINT fk_subject_student FOREIGN KEY (student_id)
    REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================
-- RISK HISTORY — trend points per term
-- ============================================================
CREATE TABLE risk_history (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  student_id  VARCHAR(30) NOT NULL,
  term        VARCHAR(40) NOT NULL,
  risk        INT         NOT NULL,
  CONSTRAINT fk_history_student FOREIGN KEY (student_id)
    REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================
-- NOTES — adviser notes on a student
-- ============================================================
CREATE TABLE notes (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  student_id  VARCHAR(30)  NOT NULL,
  date        DATE         NOT NULL,
  author      VARCHAR(120) NOT NULL,
  text        TEXT         NOT NULL,
  CONSTRAINT fk_notes_student FOREIGN KEY (student_id)
    REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================
-- ALERTS — generated by the monitoring system
-- ============================================================
CREATE TABLE alerts (
  id            VARCHAR(30) PRIMARY KEY,
  student_id    VARCHAR(30) NOT NULL,
  severity      ENUM('critical','high','medium','low') NOT NULL,
  kind          VARCHAR(40) NOT NULL,
  message       VARCHAR(255) NOT NULL,
  date          DATE NOT NULL,
  acknowledged  TINYINT(1) NOT NULL DEFAULT 0,
  INDEX idx_alerts_student (student_id),
  INDEX idx_alerts_unread  (acknowledged),
  CONSTRAINT fk_alert_student FOREIGN KEY (student_id)
    REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================
-- INTERVENTIONS — tracking actions per student
-- ============================================================
CREATE TABLE interventions (
  id          VARCHAR(30) PRIMARY KEY,
  student_id  VARCHAR(30) NOT NULL,
  type        VARCHAR(60) NOT NULL,
  status      ENUM('pending','effective','no-response') NOT NULL DEFAULT 'pending',
  assigned    VARCHAR(120) DEFAULT NULL,
  action      TEXT NOT NULL,
  date        DATE NOT NULL,
  deadline    DATE DEFAULT NULL,
  INDEX idx_iv_student (student_id),
  INDEX idx_iv_status  (status),
  CONSTRAINT fk_iv_student FOREIGN KEY (student_id)
    REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================
-- SEED — users only. No student data.
-- ON DUPLICATE KEY UPDATE makes this idempotent: re-running
-- updates existing rows instead of failing on the unique email.
-- ============================================================

INSERT INTO users (role, title, name, initials, email, password, student_id) VALUES
('adviser',    'Adviser',    'Dr. Carl Domenic Reyes', 'DM', 'carl.reyes@cmdi.edu.ph', 'adviser123',    NULL),
('instructor', 'Instructor', 'Prof. Jovic Lanao',       'PJ', 'jovic.lanao@cmdi.edu.ph', 'instructor123', NULL),
('student',    'Student',    'Jomar Pantas',             'AR', 'jomar.pantas@cmdi.edu.ph', 'student123',    NULL)
ON DUPLICATE KEY UPDATE
  role       = VALUES(role),
  title      = VALUES(title),
  name       = VALUES(name),
  initials   = VALUES(initials),
  password   = VALUES(password),
  student_id = VALUES(student_id);